usage: conda create [-h] [--clone ENV] (-n ENVIRONMENT | -p PATH) [-c CHANNEL]
                    [--use-local] [--override-channels]
                    [--repodata-fn REPODATA_FNS] [--strict-channel-priority]
                    [--no-channel-priority] [--no-deps | --only-deps]
                    [--no-pin] [--copy] [-C] [-k] [--offline] [-d] [--json]
                    [-q] [-v] [-y] [--download-only] [--show-channel-urls]
                    [--file FILE] [--no-default-packages]
                    [--solver {classic} | --experimental-solver {classic}]
                    [--dev]
                    [package_spec ...]
conda create: error: one of the arguments -n/--name -p/--prefix is required
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: qiskit-aer-gpu in /home/gharrabi/.local/lib/python3.10/site-packages (0.14.2)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/gharrabi/.local/lib/python3.10/site-packages (from qiskit-aer-gpu) (12.5.40)
Requirement already satisfied: qiskit>=0.45.2 in /home/gharrabi/.local/lib/python3.10/site-packages (from qiskit-aer-gpu) (1.1.0)
Requirement already satisfied: nvidia-cublas-cu12>=12.1.3.1 in /home/gharrabi/.local/lib/python3.10/site-packages (from qiskit-aer-gpu) (12.5.2.13)
Requirement already satisfied: numpy>=1.16.3 in /opt/rit/el9/20230413/app/linux-rhel9-x86_64_v3/gcc-11.2.1/py-numpy-1.26.3-gntgk2nwxqeex7yvi5tanbwawzn6fg2d/lib/python3.10/site-packages (from qiskit-aer-gpu) (1.26.3)
Requirement already satisfied: psutil>=5 in /home/gharrabi/.local/lib/python3.10/site-packages (from qiskit-aer-gpu) (5.9.8)
Requirement already satisfied: nvidia-cusparse-cu12>=12.1.0.106 in /home/gharrabi/.local/lib/python3.10/site-packages (from qiskit-aer-gpu) (12.4.1.24)
Requirement already satisfied: nvidia-cusolver-cu12>=11.4.5.107 in /home/gharrabi/.local/lib/python3.10/site-packages (from qiskit-aer-gpu) (11.6.2.40)
Requirement already satisfied: scipy>=1.0 in /home/gharrabi/.local/lib/python3.10/site-packages (from qiskit-aer-gpu) (1.13.1)
Requirement already satisfied: cuquantum-cu12>=23.3.0 in /home/gharrabi/.local/lib/python3.10/site-packages (from qiskit-aer-gpu) (24.3.0.post1)
Requirement already satisfied: nvidia-cuda-runtime-cu12>=12.1.105 in /home/gharrabi/.local/lib/python3.10/site-packages (from qiskit-aer-gpu) (12.5.39)
Requirement already satisfied: custatevec-cu12==1.6.0.post1 in /home/gharrabi/.local/lib/python3.10/site-packages (from cuquantum-cu12>=23.3.0->qiskit-aer-gpu) (1.6.0.post1)
Requirement already satisfied: cutensornet-cu12==2.4.0.post1 in /home/gharrabi/.local/lib/python3.10/site-packages (from cuquantum-cu12>=23.3.0->qiskit-aer-gpu) (2.4.0.post1)
Requirement already satisfied: cutensor-cu12<3,>=2.0.1 in /home/gharrabi/.local/lib/python3.10/site-packages (from cutensornet-cu12==2.4.0.post1->cuquantum-cu12>=23.3.0->qiskit-aer-gpu) (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.0 in /opt/rit/el9/20230413/app/linux-rhel9-x86_64_v3/gcc-11.2.1/py-python-dateutil-2.8.2-lnvzhivzqdozu4w6lanpns5jo6oi3zjk/lib/python3.10/site-packages (from qiskit>=0.45.2->qiskit-aer-gpu) (2.8.2)
Requirement already satisfied: sympy>=1.3 in /home/gharrabi/.local/lib/python3.10/site-packages (from qiskit>=0.45.2->qiskit-aer-gpu) (1.12.1)
Requirement already satisfied: rustworkx>=0.14.0 in /home/gharrabi/.local/lib/python3.10/site-packages (from qiskit>=0.45.2->qiskit-aer-gpu) (0.14.2)
Requirement already satisfied: dill>=0.3 in /home/gharrabi/.local/lib/python3.10/site-packages (from qiskit>=0.45.2->qiskit-aer-gpu) (0.3.8)
Requirement already satisfied: symengine>=0.11 in /home/gharrabi/.local/lib/python3.10/site-packages (from qiskit>=0.45.2->qiskit-aer-gpu) (0.11.0)
Requirement already satisfied: stevedore>=3.0.0 in /home/gharrabi/.local/lib/python3.10/site-packages (from qiskit>=0.45.2->qiskit-aer-gpu) (5.2.0)
Requirement already satisfied: typing-extensions in /home/gharrabi/.local/lib/python3.10/site-packages (from qiskit>=0.45.2->qiskit-aer-gpu) (4.12.2)
Requirement already satisfied: six>=1.5 in /opt/rit/el9/20230413/app/linux-rhel9-x86_64_v3/gcc-11.2.1/py-six-1.16.0-oydnqmzzunk2cmdr6ofjjvtgmrwmiehe/lib/python3.10/site-packages (from python-dateutil>=2.8.0->qiskit>=0.45.2->qiskit-aer-gpu) (1.16.0)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /home/gharrabi/.local/lib/python3.10/site-packages (from stevedore>=3.0.0->qiskit>=0.45.2->qiskit-aer-gpu) (6.0.0)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in /home/gharrabi/.local/lib/python3.10/site-packages (from sympy>=1.3->qiskit>=0.45.2->qiskit-aer-gpu) (1.3.0)
WARNING: There was an error checking the latest version of pip.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in /opt/rit/el9/20230413/app/linux-rhel9-x86_64_v3/gcc-11.2.1/py-matplotlib-3.8.3-fp2sij3q4xqgbltsouiqqdeqw2en7ptu/lib/python3.10/site-packages (3.8.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/rit/el9/20230413/app/linux-rhel9-x86_64_v3/gcc-11.2.1/py-kiwisolver-1.4.4-w7grjqhlo2f6h2z7xe4uqe7wtrewtts7/lib/python3.10/site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: pillow>=8 in /opt/rit/el9/20230413/app/linux-rhel9-x86_64_v3/gcc-11.2.1/py-pillow-9.5.0-uoajggrhnh6ntwzmg4jactpxa5kk3yoi/lib/python3.10/site-packages (from matplotlib) (9.5.0)
Requirement already satisfied: numpy<2,>=1.21 in /opt/rit/el9/20230413/app/linux-rhel9-x86_64_v3/gcc-11.2.1/py-numpy-1.26.3-gntgk2nwxqeex7yvi5tanbwawzn6fg2d/lib/python3.10/site-packages (from matplotlib) (1.26.3)
Requirement already satisfied: python-dateutil>=2.7 in /opt/rit/el9/20230413/app/linux-rhel9-x86_64_v3/gcc-11.2.1/py-python-dateutil-2.8.2-lnvzhivzqdozu4w6lanpns5jo6oi3zjk/lib/python3.10/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in /opt/rit/el9/20230413/app/linux-rhel9-x86_64_v3/gcc-11.2.1/py-fonttools-4.37.3-7xtroqbs2lwvlgzloddnxcvc3razon5l/lib/python3.10/site-packages (from matplotlib) (4.37.3)
Requirement already satisfied: contourpy>=1.0.1 in /opt/rit/el9/20230413/app/linux-rhel9-x86_64_v3/gcc-11.2.1/py-contourpy-1.0.7-bcz72hwbroy5upzcxlomfx35qhs6kv4v/lib/python3.10/site-packages (from matplotlib) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /opt/rit/el9/20230413/app/linux-rhel9-x86_64_v3/gcc-11.2.1/py-cycler-0.11.0-o5sb2sxrxkwckb7ka6eeufrxh2ogcltf/lib/python3.10/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/rit/el9/20230413/app/linux-rhel9-x86_64_v3/gcc-11.2.1/py-pyparsing-3.0.9-vr3wloxm23rpik7eueva3syjgmpz5gbl/lib/python3.10/site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: packaging>=20.0 in /opt/rit/el9/20230413/app/linux-rhel9-x86_64_v3/gcc-11.2.1/py-packaging-23.0-uqu2hz3j7ucdd42vor4e23acowssez3n/lib/python3.10/site-packages (from matplotlib) (23.0)
Requirement already satisfied: six>=1.5 in /opt/rit/el9/20230413/app/linux-rhel9-x86_64_v3/gcc-11.2.1/py-six-1.16.0-oydnqmzzunk2cmdr6ofjjvtgmrwmiehe/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
WARNING: There was an error checking the latest version of pip.
Traceback (most recent call last):
  File "/work/ccresearch/gharrabi/expr/exp5/exprz/thirty-bw-plot3.py", line 120, in <module>
    counts = run_qiskit_simulation(qc)
NameError: name 'run_qiskit_simulation' is not defined
Error: Script failed at iteration 0
